### ISSUE TITLE
Add support for `osx-arm64` target

### ISSUE THREAD

**Issue by GZTimeWalker** [conda-forge/pyelftools-feedstock#31]
### Comment:

Is possible to add `osx-arm64` target support?

**Comment by ocefpaf** [comment]
Can you send a PR adding it to the list in https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt ?

**Comment by GZTimeWalker** [comment]
> Can you send a PR adding it to the list in [conda-forge/conda-forge-pinning-feedstock@`main`/recipe/migrations/osx_arm64.txt](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt?rgh-link-date=2024-08-13T09%3A03%3A45Z) ?

Let me take a look.

**Comment by GZTimeWalker** [comment]
Done, I'm not sure I'm doing the right thing?

**Comment by jakirkham** [comment]
We certainly can add this to other migrators

That said, it looks like this could be `noarch: python` ( https://github.com/conda-forge/pyelftools-feedstock/issues/32 ). If we made that change that would solve this use case (and any other platforms users might want to install on)

**Comment by GZTimeWalker** [comment]
Anything else should I do? and when will the package update?

**Comment by jakirkham** [comment]
Typically wait for a migrator PR and offer to help if there are any issues

However it looks like it was created and merged earlier: https://github.com/conda-forge/pyelftools-feedstock/pull/33

So looks like this is complete
